#!/usr/bin/env node

'use strict'

var c = require("skilstak-colors")

console.log(c.clear);

function  randInt(min,max) {
  return Math.floor(Math.random() * (max - min + 1) + min);
}
var total = 0
for (var n=0; n<11; n++){
  var somerand = randInt(1,6);
  console.log("roll them dice! " + somerand);
  total = total + somerand;
}

console.log("Total: " + total);
